"""inicio

Revision ID: 43e195adbdcb
Revises: 
Create Date: 2025-08-21 08:56:40.049839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e195adbdcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('nome', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('caminho', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('competencia', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('data_publicacao', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_column('data_publicacao')
        batch_op.drop_column('competencia')
        batch_op.drop_column('caminho')
        batch_op.drop_column('nome')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
